In [1]:
# получим представление о таблице

import pandas as pd
df = pd.read_csv('power.csv', sep=',')
df

,здание,подъезд,этаж,квартира,кВтч
0,0,0,0,0,393.145226
1,0,0,0,1,531.038447
2,0,0,0,2,559.235808
3,0,0,0,3,453.154977
4,0,0,0,4,324.074795
...,...,...,...,...,...
115,1,2,3,0,181.203960
116,1,2,3,1,439.392880
117,1,2,3,2,314.881530
118,1,2,3,3,260.142618


In [2]:
# создание операции с массивом в NumPy
import numpy as np

from numpy import genfromtxt
# https://pyprog.pro/io_functions/genfromtxt.html

In [3]:
# 1.	Загрузите файл показания счетчиков power.csv

a = np.genfromtxt('power.csv', dtype= None, delimiter=",", skip_header=0, encoding="utf-8")
a

array([['здание', ' подъезд', ' этаж', ' квартира', ' кВтч'],
       ['0', ' 0', ' 0', ' 0', ' 393.1452256306512'],
       ['0', ' 0', ' 0', ' 1', ' 531.0384474216797'],
       ['0', ' 0', ' 0', ' 2', ' 559.2358075856457'],
       ['0', ' 0', ' 0', ' 3', ' 453.1549773095474'],
       ['0', ' 0', ' 0', ' 4', ' 324.0747945315578'],
       ['0', ' 0', ' 1', ' 0', ' 373.6624897943168'],
       ['0', ' 0', ' 1', ' 1', ' 346.5912626399677'],
       ['0', ' 0', ' 1', ' 2', ' 479.8857310888585'],
       ['0', ' 0', ' 1', ' 3', ' 558.3161370536229'],
       ['0', ' 0', ' 1', ' 4', ' 262.07444862461574'],
       ['0', ' 0', ' 2', ' 0', ' 411.14114479353606'],
       ['0', ' 0', ' 2', ' 1', ' 520.0233901244935'],
       ['0', ' 0', ' 2', ' 2', ' 509.17405565953266'],
       ['0', ' 0', ' 2', ' 3', ' 272.4756653875391'],
       ['0', ' 0', ' 2', ' 4', ' 404.1953457778511'],
       ['0', ' 0', ' 3', ' 0', ' 447.867128690191'],
       ['0', ' 0', ' 3', ' 1', ' 428.59679011313125'],
       ['0', ' 0'

In [4]:
# 2.	Создайте отдельный одномерный массив numpy показаний счетчика

b = np.genfromtxt('power.csv', dtype= None, delimiter=",", skip_header=1, usecols=4, encoding="utf-8")
b

array([393.14522563, 531.03844742, 559.23580759, 453.15497731,
       324.07479453, 373.66248979, 346.59126264, 479.88573109,
       558.31613705, 262.07444862, 411.14114479, 520.02339012,
       509.17405566, 272.47566539, 404.19534578, 447.86712869,
       428.59679011, 334.75986465, 174.93893332, 564.4892545 ,
       538.65992236, 506.74801857, 398.10121113, 349.33298001,
       491.38181406, 486.48523252, 375.87933695, 566.33709458,
       380.74186418, 387.16077567, 416.8442116 , 598.03328433,
       474.02501576, 362.48034871, 416.92979189, 454.39464334,
       497.41753364, 509.82674139, 272.20471493, 306.76627039,
       303.29565313, 314.69132267, 374.88454329, 473.63796487,
       411.96952507, 324.56709249, 296.69430248, 455.14188565,
       264.27191911, 559.88513624, 646.08101884, 292.13262366,
       548.27996241, 173.47384689, 618.76486794, 498.93328765,
       386.12147617, 417.18395389, 247.63763986, 430.29081794,
       428.84079815, 381.84230344, 333.48545198, 502.92

In [5]:
b.size, b.dtype

(120, dtype('float64'))

In [9]:
# 3.	Создайте многомерный массив показаний счетчика где оси куба
# a.	аxis=0 – номер дома
# b.	аxis=1 – номер подъезда
# c.	аxis=2 – номер этажа
# d.	аxis=3 – номер квартиры

dom_3d=b.reshape(2, 3, 4, 5)
dom_3d 
# описание массива как: 2 дома по 3 подъезда, по 4 этажа, по 5 квартир на этаже

array([[[[393.14522563, 531.03844742, 559.23580759, 453.15497731,
          324.07479453],
         [373.66248979, 346.59126264, 479.88573109, 558.31613705,
          262.07444862],
         [411.14114479, 520.02339012, 509.17405566, 272.47566539,
          404.19534578],
         [447.86712869, 428.59679011, 334.75986465, 174.93893332,
          564.4892545 ]],

        [[538.65992236, 506.74801857, 398.10121113, 349.33298001,
          491.38181406],
         [486.48523252, 375.87933695, 566.33709458, 380.74186418,
          387.16077567],
         [416.8442116 , 598.03328433, 474.02501576, 362.48034871,
          416.92979189],
         [454.39464334, 497.41753364, 509.82674139, 272.20471493,
          306.76627039]],

        [[303.29565313, 314.69132267, 374.88454329, 473.63796487,
          411.96952507],
         [324.56709249, 296.69430248, 455.14188565, 264.27191911,
          559.88513624],
         [646.08101884, 292.13262366, 548.27996241, 173.47384689,
          618.764867

In [10]:
# 4.	Выведите размер и форму куба 
dom_3d.shape, dom_3d.size
# описание массива как: 2 дома по 3 подъезда, по 4 этажа, по 5 квартир на этаже, всего 120 квартир.

((2, 3, 4, 5), 120)

In [11]:
# 5.	Посчитайте по всему дому:
# a.	Все потребление
# b.	Мин и макс
# c.	Среднее и дисперсию

In [12]:
dom_3d.sum(), dom_3d.min(), dom_3d.max(), dom_3d.mean(), dom_3d.std()

(48672.87333901429,
 157.3957223504202,
 646.0810188388743,
 405.60727782511907,
 102.77703189971706)

In [35]:
dom_3d.sum(axis=(0, 1, 2, 3))

48672.87333901429

In [191]:
# 6.	Посчитайте описательную статистику сгруппировав по
# a.	Домам
# b.	Подъездам
# c.	Этажам 
# d.	Квартирам

In [13]:
# a.	описательная статистика по Дому "0"

дом_1 = dom_3d[0]
дом_1.sum(), дом_1.mean(), дом_1.min(), дом_1.max(), дом_1.std()

(25176.53054095124,
 419.60884234918734,
 173.4738468921484,
 646.0810188388743,
 107.85041504418982)

In [26]:
# a.	описательная статистика по Дому "1"

дом_2 = dom_3d[1]
дом_2.sum(), дом_2.mean(), дом_2.min(), дом_2.max(), дом_2.std()

(23496.34279806305,
 391.60571330105086,
 157.3957223504202,
 622.5945434845175,
 95.40669226413637)

In [36]:
dom_3d.sum(axis=(1, 2, 3))

array([25176.53054095, 23496.34279806])

In [27]:
# b.	описательная статистика по подъезду "0" дома "0"

подъезд_11 = dom_3d[0, 0]
подъезд_11.sum(), подъезд_11.mean(), подъезд_11.min(), подъезд_11.max(), подъезд_11.std()

(8348.840894698566,
 417.4420447349283,
 174.93893332462892,
 564.4892545012378,
 106.51251628028255)

In [28]:
dom_3d[0, 0]

array([[393.14522563, 531.03844742, 559.23580759, 453.15497731,
        324.07479453],
       [373.66248979, 346.59126264, 479.88573109, 558.31613705,
        262.07444862],
       [411.14114479, 520.02339012, 509.17405566, 272.47566539,
        404.19534578],
       [447.86712869, 428.59679011, 334.75986465, 174.93893332,
        564.4892545 ]])

In [30]:
# b.	описательная статистика по подъезду "2" дома "1"

подъезд_23 = dom_3d[1, 2]
подъезд_23.sum(), подъезд_23.mean(), подъезд_23.min(), подъезд_23.max(), подъезд_23.std()

(7576.221478673852,
 378.8110739336926,
 181.20395969669295,
 506.66201085555605,
 81.9407016072431)

In [212]:
# сумма kWt по каждому этаже в двух домам

dom_3d.sum(axis = (0, 1))

array([[2793.1981536 , 2621.57475082, 2350.19543983, 2455.52908471,
        2399.50533284],
       [2581.58174587, 2405.90547243, 2544.62472755, 2415.3956163 ,
        2259.98136523],
       [2522.58211336, 2773.38510712, 2599.40110888, 1936.61754957,
        2440.00071847],
       [2445.21598869, 2674.24871871, 2194.7407774 , 1800.49385187,
        2458.69571574]])

In [232]:
# сумма kWt по квартирам
квартиры = dom_3d.sum(axis = (0, 1, 2))

In [231]:
# сумма kWt по каждой квартире "0" на каждом этаже, в каждом подъезде, в двух домам
# сумма kWt по каждой квартире "1" на каждом этаже, в каждом подъезде, в двух домам
# сумма kWt по каждой квартире "2" на каждом этаже, в каждом подъезде, в двух домам
# сумма kWt по каждой квартире "3" на каждом этаже, в каждом подъезде, в двух домам
# сумма kWt по каждой квартире "4" на каждом этаже, в каждом подъезде, в двух домам
квартиры[0], квартиры[1], квартиры[2], квартиры[3], квартиры[4]

(10342.578001522466,
 10475.114049094069,
 9688.962053654397,
 8608.036102463213,
 9558.18313228015)

In [39]:
# 7.	Посчитайте суммарное потребление по этажам каждого здания отдельно

этаж = dom_3d.sum(axis = (1, 2))
этаж

array([[5295.07705082, 5093.96778876, 5626.83586709, 3982.66699164,
        5177.98284264],
       [5047.5009507 , 5381.14626034, 4062.12618657, 4625.36911083,
        4380.20028964]])

In [40]:
# 8.	B суммарное потребление по каждому зданию

dom_3d.sum(axis=(1, 2, 3))

array([25176.53054095, 23496.34279806])